# -*- coding: utf-8 -*-
"""pothole teachable machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWswhO2WC3-b1AIT0F2ubXHF-4ro4mxS
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import os
from PIL import Image


model_path = '/content/keras_model.h5'
model = load_model(model_path)

image_dir = '/content/'
image_files = [f for f in os.listdir(image_dir) if f.endswith('.jpg')]


class_names_path = '/content/labels.txt'
with open(class_names_path, 'r') as file:
    class_names = [line.strip() for line in file.readlines()]


for img_file in image_files:
    img_path = os.path.join(image_dir, img_file)

    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0

    # Prediksi
    predictions = model.predict(img_array)
    predicted_class_index = np.argmax(predictions, axis=1)[0]
    predicted_class_name = class_names[predicted_class_index]

    img = Image.open(img_path)
    save_path = os.path.join(image_dir, f'{os.path.splitext(img_file)[0]}_predicted.jpg')

    # Tampilkan gambar
    plt.imshow(img)
    plt.title(f'Predicted class: {predicted_class_name}')
    plt.axis('off')
    plt.show()